name: MacOS_Release

# Based on: https://github.com/robpc/maze-test-game/blob/osx-test/.github/workflows/release-macos.yml

env:
  godot_version: "4.1"
  godot_release: stable
  filename: seek
  version: "0.4.1"

on:
  push:
    branches:
      - main

jobs:
  exports:
    name: Export from Godot
    strategy:
      matrix:
        include:
          - preset: macOS # must match the name of the preset in export_presets.cfg
            runner: macos-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Set Env Vars
        env:
          FILENAME: ${{ env.filename }}
          PRESET: ${{ matrix.preset }}
          VERSION: ${{ env.version }}
        run: |
          echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
          echo "package=${FILENAME}-v${VERSION}-${PRESET}.zip" >> $GITHUB_ENV
      - name: Install Godot (non-stable)
        if: ${{ matrix.preset == 'macOS' && env.godot_release != 'stable'}}
        env:
          GODOT_VERSION: ${{ env.godot_version }}
          GODOT_RELEASE: ${{ env.godot_release }}
        run: |
          export GODOT_FULL_VERSION="${GODOT_VERSION}-${GODOT_RELEASE}"
          echo "$GODOT_FULL_VERSION"
          export XDG_DATA_HOME="$(pwd)/xdg_data_home"
          export TEMPLATES_DIR="${XDG_DATA_HOME}/Godot/export_templates/${GODOT_VERSION}.${GODOT_RELEASE}/"
          
          wget -q https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/${GODOT_RELEASE}/Godot_v${GODOT_FULL_VERSION}_macos.universal.zip
          unzip Godot_v${GODOT_FULL_VERSION}_macos.universal.zip

          mkdir -p ${TEMPLATES_DIR}
          wget -q https://github.com/GodotBuilder/godot-builds/releases/download/${GODOT_VERSION}-prerelease-templates/Godot_v${GODOT_FULL_VERSION}_export_templates.tpz
          unzip Godot_v${GODOT_FULL_VERSION}_export_templates.tpz
          mv -v templates/* ${TEMPLATES_DIR}
      - name: Install Godot (stable)
        if: ${{ matrix.preset == 'macOS' && env.godot_release == 'stable'}}
        env:
          GODOT_VERSION: ${{ env.godot_version }}
          GODOT_RELEASE: ${{ env.godot_release }}
        run: |
          export GODOT_FULL_VERSION="${GODOT_VERSION}-${GODOT_RELEASE}"
          echo "$GODOT_FULL_VERSION"
          export XDG_DATA_HOME="$(pwd)/xdg_data_home"
          export TEMPLATES_DIR="${XDG_DATA_HOME}/Godot/export_templates/${GODOT_VERSION}.${GODOT_RELEASE}/"
          
          wget -q https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_FULL_VERSION}_macos.universal.zip
          unzip Godot_v${GODOT_FULL_VERSION}_macos.universal.zip

          mkdir -p ${TEMPLATES_DIR}
          wget -q https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_FULL_VERSION}_export_templates.tpz
          unzip Godot_v${GODOT_FULL_VERSION}_export_templates.tpz
          mv -v templates/* ${TEMPLATES_DIR}
      - name: Export macOS
        if: ${{ matrix.preset == 'macOS' }}
        env:
          PRESET: ${{ matrix.preset }}
          BUILD_DIR: build
          FILENAME: ${{ env.package }}
        run: |
          export XDG_DATA_HOME="$(pwd)/xdg_data_home"
          export TEMPLATES_DIR="${XDG_DATA_HOME}/Godot/export_templates/${GODOT_VERSION}.${GODOT_RELEASE}/"

          mkdir -p ${XDG_DATA_HOME}/.godot
          mkdir -p ${BUILD_DIR}
          Godot.app/Contents/MacOS/Godot --headless --export-release ${PRESET} ${BUILD_DIR}/${FILENAME}
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.package }}
          path: build/${{ env.package }}
